//! Byte-level BPE tokenizer in the GPT-2 vocab.json/merges.txt format - the
//! tokenizer milestone M3 needs to feed real checkpoints. Pure std, no
//! dependencies, no dependency on ferro-core.
//!
//! The pipeline is exactly the reference implementation's:
//! 1. Pre-tokenize the text with GPT-2's split rule (hand-rolled here; the
//!    original is the regex `'(?:[sdmt]|ll|ve|re)| ?\p{L}+| ?\p{N}+|
//!    ?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+`, whose observable behavior is:
//!    contractions split off; a single LITERAL SPACE attaches to a following
//!    letter/number/symbol run; a whitespace run followed by a token yields
//!    the run minus its last character; trailing whitespace stays whole).
//! 2. Map each piece's UTF-8 bytes through the byte<->unicode table (every
//!    byte becomes a printable char, so the vocab holds no raw control
//!    bytes and any byte sequence is representable).
//! 3. Run ranked BPE merges over the mapped piece and look the resulting
//!    tokens up in the vocab.
//!
//! Decoding inverts: ids -> vocab strings -> bytes -> UTF-8 (lossy on
//! invalid boundaries, matching the reference decoder's errors="replace").

use std::collections::HashMap;
use std::fmt;
use std::path::Path;
use std::sync::Mutex;

#[derive(Debug)]
pub enum TokenizerError {
    Io(String),
    Format(String),
    /// A piece produced a BPE symbol absent from the vocab (a complete
    /// byte-level vocab contains all 256 single-byte tokens, so this only
    /// happens with truncated/custom vocabularies).
    UnknownToken(String),
    UnknownId(u32),
}

impl fmt::Display for TokenizerError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TokenizerError::Io(m) => write!(f, "tokenizer io: {m}"),
            TokenizerError::Format(m) => write!(f, "tokenizer format: {m}"),
            TokenizerError::UnknownToken(t) => write!(f, "token {t:?} is not in the vocab"),
            TokenizerError::UnknownId(id) => write!(f, "id {id} is not in the vocab"),
        }
    }
}

impl std::error::Error for TokenizerError {}

type Result<T> = std::result::Result<T, TokenizerError>;

/// GPT-2's byte<->unicode table: printable latin-1 bytes map to themselves,
/// every other byte to U+0100 + counter, giving a 256-way bijection into
/// printable chars.
fn byte_to_unicode() -> [char; 256] {
    let mut table = ['\0'; 256];
    let mut n = 0u32;
    for b in 0u32..256 {
        let printable =
            (33..=126).contains(&b) || (161..=172).contains(&b) || (174..=255).contains(&b);
        table[b as usize] = if printable {
            char::from_u32(b).unwrap()
        } else {
            let c = char::from_u32(256 + n).unwrap();
            n += 1;
            c
        };
    }
    table
}

// --- unicode letter/number classes -----------------------------------------
// The reference pre-tokenizer's \p{L}/\p{N} are Unicode GENERAL CATEGORIES;
// Rust's char::is_alphabetic is the broader Alphabetic PROPERTY: L* plus Nl
// (letter numbers, e.g. Roman numerals) plus ~1400 Other_Alphabetic
// combining marks and signs. The difference changes token ids: U+0345
// COMBINING GREEK YPOGEGRAMMENI must split off as a symbol piece and a
// Roman numeral belongs to the number piece. is_number needs no correction
// (char::is_numeric is exactly N*); is_letter subtracts Nl via is_numeric
// and the mark/sign residue via the table below.

/// Whether `c` has Unicode general category Letter (Lu/Ll/Lt/Lm/Lo) - exactly
/// the reference tokenizer's `\p{L}`. Public so tests (and callers building
/// their own splitters) can check the classification directly rather than
/// only through `pretokenize`'s output shape.
pub fn is_letter(c: char) -> bool {
    c.is_alphabetic() && !c.is_numeric() && !in_other_alphabetic(c)
}

/// Unicode general category Number (Nd/Nl/No) - exactly `\p{N}`.
pub fn is_number(c: char) -> bool {
    c.is_numeric()
}

fn in_other_alphabetic(c: char) -> bool {
    let cp = c as u32;
    OTHER_ALPHABETIC
        .binary_search_by(|&(lo, hi)| {
            if hi < cp {
                std::cmp::Ordering::Less
            } else if lo > cp {
                std::cmp::Ordering::Greater
            } else {
                std::cmp::Ordering::Equal
            }
        })
        .is_ok()
}

/// Alphabetic-but-not-\p{L} codepoints (general categories Mn/Mc/Me/So with
/// the Other_Alphabetic property), as sorted inclusive ranges. Generated by
/// dumping every char::is_alphabetic codepoint from rustc and classifying
/// with Unicode 14 general categories; codepoints unassigned in that table
/// are excluded (they are newly assigned LETTERS in the std tables, not
/// category differences).
const OTHER_ALPHABETIC: &[(u32, u32)] = &[
    (0x0345, 0x0345), (0x0363, 0x036F), (0x05B0, 0x05BD), (0x05BF, 0x05BF),
    (0x05C1, 0x05C2), (0x05C4, 0x05C5), (0x05C7, 0x05C7), (0x0610, 0x061A),
    (0x064B, 0x0657), (0x0659, 0x065F), (0x0670, 0x0670), (0x06D6, 0x06DC),
    (0x06E1, 0x06E4), (0x06E7, 0x06E8), (0x06ED, 0x06ED), (0x0711, 0x0711),
    (0x0730, 0x073F), (0x07A6, 0x07B0), (0x0816, 0x0817), (0x081B, 0x0823),
    (0x0825, 0x0827), (0x0829, 0x082C), (0x08D4, 0x08DF), (0x08E3, 0x08E9),
    (0x08F0, 0x0903), (0x093A, 0x093B), (0x093E, 0x094C), (0x094E, 0x094F),
    (0x0955, 0x0957), (0x0962, 0x0963), (0x0981, 0x0983), (0x09BE, 0x09C4),
    (0x09C7, 0x09C8), (0x09CB, 0x09CC), (0x09D7, 0x09D7), (0x09E2, 0x09E3),
    (0x0A01, 0x0A03), (0x0A3E, 0x0A42), (0x0A47, 0x0A48), (0x0A4B, 0x0A4C),
    (0x0A51, 0x0A51), (0x0A70, 0x0A71), (0x0A75, 0x0A75), (0x0A81, 0x0A83),
    (0x0ABE, 0x0AC5), (0x0AC7, 0x0AC9), (0x0ACB, 0x0ACC), (0x0AE2, 0x0AE3),
    (0x0AFA, 0x0AFC), (0x0B01, 0x0B03), (0x0B3E, 0x0B44), (0x0B47, 0x0B48),
    (0x0B4B, 0x0B4C), (0x0B56, 0x0B57), (0x0B62, 0x0B63), (0x0B82, 0x0B82),
    (0x0BBE, 0x0BC2), (0x0BC6, 0x0BC8), (0x0BCA, 0x0BCC), (0x0BD7, 0x0BD7),
    (0x0C00, 0x0C04), (0x0C3E, 0x0C44), (0x0C46, 0x0C48), (0x0C4A, 0x0C4C),
    (0x0C55, 0x0C56), (0x0C62, 0x0C63), (0x0C81, 0x0C83), (0x0CBE, 0x0CC4),
    (0x0CC6, 0x0CC8), (0x0CCA, 0x0CCC), (0x0CD5, 0x0CD6), (0x0CE2, 0x0CE3),
    (0x0D00, 0x0D03), (0x0D3E, 0x0D44), (0x0D46, 0x0D48), (0x0D4A, 0x0D4C),
    (0x0D57, 0x0D57), (0x0D62, 0x0D63), (0x0D81, 0x0D83), (0x0DCF, 0x0DD4),
    (0x0DD6, 0x0DD6), (0x0DD8, 0x0DDF), (0x0DF2, 0x0DF3), (0x0E31, 0x0E31),
    (0x0E34, 0x0E3A), (0x0E4D, 0x0E4D), (0x0EB1, 0x0EB1), (0x0EB4, 0x0EB9),
    (0x0EBB, 0x0EBC), (0x0ECD, 0x0ECD), (0x0F71, 0x0F83), (0x0F8D, 0x0F97),
    (0x0F99, 0x0FBC), (0x102B, 0x1036), (0x1038, 0x1038), (0x103B, 0x103E),
    (0x1056, 0x1059), (0x105E, 0x1060), (0x1062, 0x1064), (0x1067, 0x106D),
    (0x1071, 0x1074), (0x1082, 0x108D), (0x108F, 0x108F), (0x109A, 0x109D),
    (0x1712, 0x1713), (0x1732, 0x1733), (0x1752, 0x1753), (0x1772, 0x1773),
    (0x17B6, 0x17C8), (0x1885, 0x1886), (0x18A9, 0x18A9), (0x1920, 0x192B),
    (0x1930, 0x1938), (0x1A17, 0x1A1B), (0x1A55, 0x1A5E), (0x1A61, 0x1A74),
    (0x1ABF, 0x1AC0), (0x1ACC, 0x1ACE), (0x1B00, 0x1B04), (0x1B35, 0x1B43),
    (0x1B80, 0x1B82), (0x1BA1, 0x1BA9), (0x1BAC, 0x1BAD), (0x1BE7, 0x1BF1),
    (0x1C24, 0x1C36), (0x1DD3, 0x1DF4), (0x24B6, 0x24E9), (0x2DE0, 0x2DFF),
    (0xA674, 0xA67B), (0xA69E, 0xA69F), (0xA802, 0xA802), (0xA80B, 0xA80B),
    (0xA823, 0xA827), (0xA880, 0xA881), (0xA8B4, 0xA8C3), (0xA8C5, 0xA8C5),
    (0xA8FF, 0xA8FF), (0xA926, 0xA92A), (0xA947, 0xA952), (0xA980, 0xA983),
    (0xA9B4, 0xA9BF), (0xA9E5, 0xA9E5), (0xAA29, 0xAA36), (0xAA43, 0xAA43),
    (0xAA4C, 0xAA4D), (0xAA7B, 0xAA7D), (0xAAB0, 0xAAB0), (0xAAB2, 0xAAB4),
    (0xAAB7, 0xAAB8), (0xAABE, 0xAABE), (0xAAEB, 0xAAEF), (0xAAF5, 0xAAF5),
    (0xABE3, 0xABEA), (0xFB1E, 0xFB1E), (0x10376, 0x1037A), (0x10A01, 0x10A03),
    (0x10A05, 0x10A06), (0x10A0C, 0x10A0F), (0x10D24, 0x10D27), (0x10EAB, 0x10EAC),
    (0x11000, 0x11002), (0x11038, 0x11045), (0x11073, 0x11074), (0x11080, 0x11082),
    (0x110B0, 0x110B8), (0x110C2, 0x110C2), (0x11100, 0x11102), (0x11127, 0x11132),
    (0x11145, 0x11146), (0x11180, 0x11182), (0x111B3, 0x111BF), (0x111CE, 0x111CF),
    (0x1122C, 0x11234), (0x11237, 0x11237), (0x1123E, 0x1123E), (0x112DF, 0x112E8),
    (0x11300, 0x11303), (0x1133E, 0x11344), (0x11347, 0x11348), (0x1134B, 0x1134C),
    (0x11357, 0x11357), (0x11362, 0x11363), (0x11435, 0x11441), (0x11443, 0x11445),
    (0x114B0, 0x114C1), (0x115AF, 0x115B5), (0x115B8, 0x115BE), (0x115DC, 0x115DD),
    (0x11630, 0x1163E), (0x11640, 0x11640), (0x116AB, 0x116B5), (0x1171D, 0x1172A),
    (0x1182C, 0x11838), (0x11930, 0x11935), (0x11937, 0x11938), (0x1193B, 0x1193C),
    (0x11940, 0x11940), (0x11942, 0x11942), (0x119D1, 0x119D7), (0x119DA, 0x119DF),
    (0x119E4, 0x119E4), (0x11A01, 0x11A0A), (0x11A35, 0x11A39), (0x11A3B, 0x11A3E),
    (0x11A51, 0x11A5B), (0x11A8A, 0x11A97), (0x11C2F, 0x11C36), (0x11C38, 0x11C3E),
    (0x11C92, 0x11CA7), (0x11CA9, 0x11CB6), (0x11D31, 0x11D36), (0x11D3A, 0x11D3A),
    (0x11D3C, 0x11D3D), (0x11D3F, 0x11D41), (0x11D43, 0x11D43), (0x11D47, 0x11D47),
    (0x11D8A, 0x11D8E), (0x11D90, 0x11D91), (0x11D93, 0x11D96), (0x11EF3, 0x11EF6),
    (0x16F4F, 0x16F4F), (0x16F51, 0x16F87), (0x16F8F, 0x16F92), (0x16FF0, 0x16FF1),
    (0x1BC9E, 0x1BC9E), (0x1E000, 0x1E006), (0x1E008, 0x1E018), (0x1E01B, 0x1E021),
    (0x1E023, 0x1E024), (0x1E026, 0x1E02A), (0x1E947, 0x1E947), (0x1F130, 0x1F149),
    (0x1F150, 0x1F169), (0x1F170, 0x1F189),
];

/// GPT-2's pre-tokenization split (see module docs). Public for tests and
/// for callers that want the raw pieces.
pub fn pretokenize(text: &str) -> Vec<String> {
    let chars: Vec<char> = text.chars().collect();
    let n = chars.len();
    let mut out = Vec::new();
    let mut i = 0;
    let emit = |out: &mut Vec<String>, chars: &[char], a: usize, b: usize| {
        out.push(chars[a..b].iter().collect());
    };
    while i < n {
        // Contractions: '(?:[sdmt]|ll|ve|re), single-letter suffixes first
        // like the regex alternation.
        if chars[i] == '\'' && i + 1 < n {
            let c1 = chars[i + 1];
            if matches!(c1, 's' | 'd' | 'm' | 't') {
                emit(&mut out, &chars, i, i + 2);
                i += 2;
                continue;
            }
            if i + 2 < n {
                let two = [c1, chars[i + 2]];
                if two == ['l', 'l'] || two == ['v', 'e'] || two == ['r', 'e'] {
                    emit(&mut out, &chars, i, i + 3);
                    i += 3;
                    continue;
                }
            }
        }
        // ` ?` + letter/number/other runs. Only a literal space attaches.
        let (run_start, first) = if chars[i] == ' ' && i + 1 < n {
            (i + 1, chars[i + 1])
        } else {
            (i, chars[i])
        };
        let other = |c: char| !c.is_whitespace() && !is_letter(c) && !is_number(c);
        let class: Option<fn(char) -> bool> = if is_letter(first) {
            Some(is_letter)
        } else if is_number(first) {
            Some(is_number)
        } else if other(first) {
            Some(|c| !c.is_whitespace() && !is_letter(c) && !is_number(c))
        } else {
            None
        };
        if let Some(in_class) = class {
            let mut j = run_start;
            while j < n && in_class(chars[j]) {
                // A contraction interrupts an "other" run only via the next
                // alternation round; the regex's greedy class run does not
                // look ahead, and neither do we.
                j += 1;
            }
            emit(&mut out, &chars, i, j);
            i = j;
            continue;
        }
        // Whitespace: `\s+(?!\S)` then `\s+`. A run followed by a token
        // yields the run minus its final character (the regex backtracks
        // exactly one step); at end of text the whole run matches.
        debug_assert!(chars[i].is_whitespace());
        let mut j = i;
        while j < n && chars[j].is_whitespace() {
            j += 1;
        }
        let end = if j < n && j - i > 1 { j - 1 } else { j };
        emit(&mut out, &chars, i, end);
        i = end;
    }
    out
}

/// Byte-level BPE tokenizer over a GPT-2-format vocab.
pub struct Bpe {
    encoder: HashMap<String, u32>,
    decoder: HashMap<u32, String>,
    merges: HashMap<(String, String), u32>,
    byte_enc: [char; 256],
    byte_dec: HashMap<char, u8>,
    /// Per-piece BPE results; text repeats pieces constantly and the merge
    /// loop is the expensive part.
    cache: Mutex<HashMap<String, Vec<u32>>>,
}

impl Bpe {
    /// Build from the contents of vocab.json and merges.txt.
    pub fn from_strs(vocab_json: &str, merges_txt: &str) -> Result<Bpe> {
        let encoder = parse_vocab_json(vocab_json)?;
        let mut decoder = HashMap::with_capacity(encoder.len());
        for (tok, &id) in &encoder {
            if decoder.insert(id, tok.clone()).is_some() {
                return Err(TokenizerError::Format(format!("duplicate id {id} in vocab")));
            }
        }
        let mut merges = HashMap::new();
        for (rank, line) in merges_txt
            .lines()
            .filter(|l| !l.trim().is_empty() && !l.starts_with("#version"))
            .enumerate()
        {
            let mut it = line.split_whitespace();
            let (Some(a), Some(b), None) = (it.next(), it.next(), it.next()) else {
                return Err(TokenizerError::Format(format!(
                    "merges line {rank} is not exactly two symbols: {line:?}"
                )));
            };
            merges.insert((a.to_string(), b.to_string()), rank as u32);
        }
        let byte_enc = byte_to_unicode();
        let byte_dec = byte_enc
            .iter()
            .enumerate()
            .map(|(b, &c)| (c, b as u8))
            .collect();
        Ok(Bpe {
            encoder,
            decoder,
            merges,
            byte_enc,
            byte_dec,
            cache: Mutex::new(HashMap::new()),
        })
    }

    pub fn from_files<P: AsRef<Path>>(vocab: P, merges: P) -> Result<Bpe> {
        let read = |p: &Path| {
            std::fs::read_to_string(p)
                .map_err(|e| TokenizerError::Io(format!("{}: {e}", p.display())))
        };
        Bpe::from_strs(&read(vocab.as_ref())?, &read(merges.as_ref())?)
    }

    pub fn vocab_size(&self) -> usize {
        self.encoder.len()
    }

    /// Direct vocab lookup (e.g. `token_id("<|endoftext|>")` for the eot id).
    pub fn token_id(&self, token: &str) -> Option<u32> {
        self.encoder.get(token).copied()
    }

    pub fn encode(&self, text: &str) -> Result<Vec<u32>> {
        let mut out = Vec::new();
        for piece in pretokenize(text) {
            if let Some(ids) = self.cache.lock().unwrap().get(&piece) {
                out.extend_from_slice(ids);
                continue;
            }
            let mapped: String = piece.bytes().map(|b| self.byte_enc[b as usize]).collect();
            let mut ids = Vec::new();
            for sym in self.bpe(&mapped) {
                match self.encoder.get(&sym) {
                    Some(&id) => ids.push(id),
                    None => return Err(TokenizerError::UnknownToken(sym)),
                }
            }
            out.extend_from_slice(&ids);
            self.cache.lock().unwrap().insert(piece, ids);
        }
        Ok(out)
    }

    pub fn decode(&self, ids: &[u32]) -> Result<String> {
        let mut bytes = Vec::new();
        for &id in ids {
            let tok = self
                .decoder
                .get(&id)
                .ok_or(TokenizerError::UnknownId(id))?;
            for c in tok.chars() {
                match self.byte_dec.get(&c) {
                    Some(&b) => bytes.push(b),
                    None => {
                        return Err(TokenizerError::Format(format!(
                            "token {tok:?} contains {c:?}, outside the byte table"
                        )))
                    }
                }
            }
        }
        // Lossy: token boundaries can split UTF-8 sequences mid-character
        // (the reference decoder uses errors="replace" for the same reason).
        Ok(String::from_utf8_lossy(&bytes).into_owned())
    }

    /// The ranked merge loop: repeatedly replace every occurrence of the
    /// lowest-ranked adjacent symbol pair until none remains.
    fn bpe(&self, mapped: &str) -> Vec<String> {
        let mut word: Vec<String> = mapped.chars().map(|c| c.to_string()).collect();
        while word.len() > 1 {
            let mut best: Option<(u32, (String, String))> = None;
            for pair in word.windows(2) {
                let key = (pair[0].clone(), pair[1].clone());
                if let Some(&rank) = self.merges.get(&key) {
                    if best.as_ref().is_none_or(|(r, _)| rank < *r) {
                        best = Some((rank, key));
                    }
                }
            }
            let Some((_, (a, b))) = best else { break };
            let mut merged = Vec::with_capacity(word.len());
            let mut i = 0;
            while i < word.len() {
                if i + 1 < word.len() && word[i] == a && word[i + 1] == b {
                    merged.push(format!("{a}{b}"));
                    i += 2;
                } else {
                    merged.push(std::mem::take(&mut word[i]));
                    i += 1;
                }
            }
            word = merged;
        }
        word
    }
}

/// Minimal parser for vocab.json: one flat JSON object mapping token strings
/// to unsigned integer ids. Handles the full string escape set including
/// \uXXXX with surrogate pairs; anything structurally different errors.
fn parse_vocab_json(src: &str) -> Result<HashMap<String, u32>> {
    let b: Vec<char> = src.chars().collect();
    let mut i = 0;
    let err = |m: &str, at: usize| TokenizerError::Format(format!("vocab.json at {at}: {m}"));
    let skip_ws = |i: &mut usize| {
        while *i < b.len() && b[*i].is_whitespace() {
            *i += 1;
        }
    };
    skip_ws(&mut i);
    if i >= b.len() || b[i] != '{' {
        return Err(err("expected '{'", i));
    }
    i += 1;
    let mut out = HashMap::new();
    skip_ws(&mut i);
    if i < b.len() && b[i] == '}' {
        return Ok(out);
    }
    loop {
        skip_ws(&mut i);
        let key = parse_string(&b, &mut i)?;
        skip_ws(&mut i);
        if i >= b.len() || b[i] != ':' {
            return Err(err("expected ':'", i));
        }
        i += 1;
        skip_ws(&mut i);
        let start = i;
        while i < b.len() && b[i].is_ascii_digit() {
            i += 1;
        }
        if start == i {
            return Err(err("expected an unsigned integer id", i));
        }
        let id: u32 = b[start..i]
            .iter()
            .collect::<String>()
            .parse()
            .map_err(|_| err("id out of range", start))?;
        if out.insert(key.clone(), id).is_some() {
            return Err(TokenizerError::Format(format!("duplicate token {key:?}")));
        }
        skip_ws(&mut i);
        match b.get(i) {
            Some(',') => i += 1,
            Some('}') => return Ok(out),
            _ => return Err(err("expected ',' or '}'", i)),
        }
    }
}

fn parse_string(b: &[char], i: &mut usize) -> Result<String> {
    let err = |m: &str, at: usize| TokenizerError::Format(format!("vocab.json at {at}: {m}"));
    if *i >= b.len() || b[*i] != '"' {
        return Err(err("expected '\"'", *i));
    }
    *i += 1;
    let mut s = String::new();
    loop {
        let c = *b.get(*i).ok_or_else(|| err("unterminated string", *i))?;
        *i += 1;
        match c {
            '"' => return Ok(s),
            '\\' => {
                let e = *b.get(*i).ok_or_else(|| err("unterminated escape", *i))?;
                *i += 1;
                match e {
                    '"' => s.push('"'),
                    '\\' => s.push('\\'),
                    '/' => s.push('/'),
                    'b' => s.push('\u{0008}'),
                    'f' => s.push('\u{000C}'),
                    'n' => s.push('\n'),
                    'r' => s.push('\r'),
                    't' => s.push('\t'),
                    'u' => {
                        let hi = parse_hex4(b, i)?;
                        let cp = if (0xD800..=0xDBFF).contains(&hi) {
                            // Surrogate pair: require the low half.
                            if b.get(*i) != Some(&'\\') || b.get(*i + 1) != Some(&'u') {
                                return Err(err("unpaired high surrogate", *i));
                            }
                            *i += 2;
                            let lo = parse_hex4(b, i)?;
                            if !(0xDC00..=0xDFFF).contains(&lo) {
                                return Err(err("invalid low surrogate", *i));
                            }
                            0x10000 + ((hi - 0xD800) << 10) + (lo - 0xDC00)
                        } else {
                            hi
                        };
                        s.push(char::from_u32(cp).ok_or_else(|| err("invalid codepoint", *i))?);
                    }
                    _ => return Err(err("unknown escape", *i)),
                }
            }
            _ => s.push(c),
        }
    }
}

fn parse_hex4(b: &[char], i: &mut usize) -> Result<u32> {
    let err = |at: usize| TokenizerError::Format(format!("vocab.json at {at}: bad \\u escape"));
    let mut v = 0u32;
    for _ in 0..4 {
        let c = *b.get(*i).ok_or_else(|| err(*i))?;
        *i += 1;
        v = v * 16 + c.to_digit(16).ok_or_else(|| err(*i))?;
    }
    Ok(v)
}
